### ISSUE TITLE
Windows fix

### ISSUE THREAD

**Issue by PAEz** [surrim/vlc-delete#1]
To lazy to do a pull right now, if ever, soooo......
https://gist.github.com/PAEz/d3a9be2471dbd39084136d974cdb9dd3

As I state in the comment I dont know lua but this seems to be working so far.
Thanks for sharing your code ;P

**Comment by surrim** [comment]
Thanks PAEz, I applied the changes: https://github.com/surrim/vlc-delete/commit/675656fc5dd86a31d0f4fde00121699038c3f10a

**Comment by PAEz** [comment]
Last one was a little flakey. Ive made it more robust.  Cleaned out a directory of stuff with it and no probs now.
Sorry.

**Comment by surrim** [comment]
Did you test with Windows?

**Comment by PAEz** [comment]
yeah, im on windows 10

**Comment by surrim** [comment]
I fixed it again, see https://github.com/surrim/vlc-delete/commit/f80ed9b249cfc21418edf2e43e01729fd50e4e2a. Thanks for sharing :)
