### ISSUE TITLE
Shortcut key

### ISSUE THREAD

**Issue by MonolithAU** [surrim/vlc-delete#10]
Thanks for your work on this! A shortcut key option would be a huge improvement for this extention. I would love to map it to a button on my Stream Deck to quickly delete files from a playlist as I review them.

**Comment by Deadly35** [comment]
Definitely! That'd be so useful

**Comment by forplan0** [comment]
Please add Shortcut key

**Comment by surrim** [comment]
:heavy_check_mark: I'm closing this bug. The current implementation is working, see `README.md`. I have also added an animated picture for illustration.

**Comment by MonolithAU** [comment]
Thanks very much! Very handy addition to my Stream Deck
