### ISSUE TITLE
Don't know if this plugin works in other OSes, but in Windows (10/11) it surely didn't work, so I had to do many fixes and turn this plugin into Windows only using only core Windows batch functions for operations

### ISSUE THREAD

**Issue by vivek1986** [surrim/vlc-delete#11]
Don't know if this plugin works in other OSes, but in Windows (10/11) it surely didn't work, so I had to do many fixes and turn this plugin into Windows only using only core Windows batch functions for operations.

So in hopes that this inspires others here to rectify the errors in the Lua libraries so that they don't throw errors when dealing with File I/O operations in  Windows, here's the code and [the Stackoverflow page](https://stackoverflow.com/a/73131314/365107) where also I mentioned this as an answer to my own question:

```lua
-- Copy this file to %ProgramFiles%\VideoLAN\VLC\lua\extensions\ and restart VLC Media player.
function descriptor()
    return {
        title = "VLC Delete Media File(Windows only)";
        version = "1.0";
        author = "Vicky Dev";
        shortdesc = "&Remove current file from playlist and disk";
        description = [[
<h1>VLC Delete Media File(Windows only)</h1>"
When you're playing a file, use this to easily
delete the current file from your <b>playlist</b> and <b>disk</b> with one click.<br>
Disclaimer: The author is not responsible for damage caused by this extension.
        ]];
    }
end

function sleep(seconds)
    local t0 = os.clock()
    local tOriginal = t0
    while os.clock() - t0 <= seconds and os.clock() >= tOriginal do end
end

function removeItem()
    local id = vlc.playlist.current()
    vlc.playlist.delete(id)
    vlc.playlist.gotoitem(id + 1)
    vlc.deactivate()
end

function activate()
    local item = vlc.input.item()
    local uri = item:uri()
    uri = string.gsub(uri, "^file:///", "")
    uri = vlc.strings.decode_uri(uri)
    path = string.gsub(uri, "/", "\\")
    vlc.msg.info("[VLC Delete Media File(Windows only)] removing: "..uri.." : "..path)
    removeItem()
    retval, err = os.execute("if exist ".."\""..path.."\"".." @(call )")
    if (type(retval) == 'number' and retval == 0) then
        os.execute("del /f /a /q ".."\""..path.."\"")
    end
end

function click_ok()
    d:delete()
    vlc.deactivate()
end

function deactivate()
    vlc.deactivate()
end

function close()
    deactivate()
end

function meta_changed()
end
```

**Comment by surrim** [comment]
> Don't know if this plugin works in other OSes, but in Windows (10/11) it surely didn't work, so I had to do many fixes and turn this plugin into Windows only using only core Windows batch functions for operations.
> 
> [...]

Thanks for your investigations(!) 🤗

Could you please create a pull request to the new branch https://github.com/surrim/vlc-delete/tree/master-windows-only if possible? At the moment I don't have a PC with me. Maybe somebody else could modify the branch that I can later merge it back into the master branch. I'm really no Lua expert :)

**Comment by surrim** [comment]
> @surrim I tried but I am getting this error when I try to push from my local repo copy to origin(master-windows-only):
> 
> ```
> remote: Permission to surrim/vlc-delete.git denied to vivek1986.
> fatal: unable to access 'https://github.com/surrim/vlc-delete.git/': The requested URL returned error: 403
> ```

You can fork this project, then push to your own, and finally create a pull request on GitHub 😉

**Comment by surrim** [comment]
Applied changes with commit https://github.com/surrim/vlc-delete/commit/539dc60a2f41f51d74884e335ac465d6d597c680, and some more 🚀

**Comment by surrim** [comment]
Should be finally working with commit https://github.com/surrim/vlc-delete/commit/6f5f2766118870a73dd42a0a7100f53ff31b33c5, see also https://github.com/surrim/vlc-delete/issues/15 🚀
