### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by barbuslex** [surrim/vlc-delete#12]
Hi,
Is it possible to add a shortcut on DELETE key on keyboard ?
Thanks

**Comment by surrim** [comment]
Hey there, I made this plugin for myself and would also love to include a real hotkey. Sadly it seems that it is [not possible for LUA extensions](https://github.com/surrim/vlc-delete/issues/3#issuecomment-753032966).
It would be the best if VLC would implement the delete feature itself - it's also included in their mobile app and almost every picture viewer.
