### ISSUE TITLE
Restarts playlist (Ubuntu)

### ISSUE THREAD

**Issue by itsme9** [surrim/vlc-delete#13]
Hi, when 2 videos in a row are deleted it goes back the first video in the playlist.
thanks

**Comment by surrim** [comment]
Thanks for feedback, same here (Fedora)

**Comment by surrim** [comment]
Please check again @itsme9, it should be fixed with https://github.com/surrim/vlc-delete/commit/94534e50ba46bd1715d068068ce4889b4066c66f from today 😉

**Comment by itsme9** [comment]
Thanks works great now
