### ISSUE TITLE
Nothing on view menu (windows 10, VLC 3.0.18)

### ISSUE THREAD

**Issue by ovnis82** [surrim/vlc-delete#14]
Hello!

I have installed vlc-delete.lua inside "C:\Program Files\VideoLAN\VLC\lua\extensions" but nothing inside view menu.

How to fix that ? 

Thx!

**Comment by surrim** [comment]
Hello @ovnis82 , are other extensions working?

**Comment by ovnis82** [comment]
Yes. I can see and open them.

**Comment by saiedgerami** [comment]
Same for me. Nothing in the view other than the native VLsub.

**Comment by surrim** [comment]
Can you try to copy the lua file to `%appdata%\Roaming\vlc\lua\extensions` (something like `C:\Users\UserName\AppData\Roaming\vlc\lua\extensions`)?
If it's working, please leave some feedback - so I can update the readme file 🚀

See [Installing Extensions in lua](https://docs.videolan.me/vlc-user/3.0/en/addons/extensions.html#installing-extensions-in-lua).

**Comment by searkes** [comment]
I also have this issue. Nothing on the view menu but the extension is showing up as loaded. 
VLC 3.0.18   just got the latest lua file from the site for the plug in. Still nothing shows up in view for VLC player.

**Comment by log1co** [comment]
I **had** the same issue with VLC 3.0.18 on Windows 10. I tried another extension and it was not showing up either.

I resolved the issue by copying the .lua files to _C:/Program Files (x86)/Video Lan/VLC/lua/extensions_ (instead of the _%appdata%\Roaming\vlc\lua\extensions\_). Then I clicked "Reload Extensions" in VLC (Tools > Plugins and Extensions > Active Extensions) and voila.

**Comment by fun29** [comment]
Or when you unpack VLC and install without using the installer.

Then putting the lua in this dir works without any problem:
C:\MyInstalledApps\vlc-3.0.18\lua\extensions\

**Comment by Alucard87** [comment]
Hello,

ich have the solution for this problem (which will occur on any Windows).

The path you are showing is incorrect.
Instead of "%appdata%\Roaming\vlc\lua\extensions\" it must be "%appdata%\vlc\lua\extensions\"
because %appdata% is already linking to the Roaming-Folder.

Best Regards
Alucard

**Comment by surrim** [comment]
> The path you are using is incorrect. Instead of "%appdata%\Roaming\vlc\lua\extensions" it must be "%appdata%\vlc\lua\extensions" because %appdata% is already linking to the Roaming-Folder.

Merged with https://github.com/surrim/vlc-delete/pull/21. If there's still trouble to get the plugin loaded, please reopen/recreate this issue.
