### ISSUE TITLE
Delete from filesystem does not work: Win10 64bit VLC 3.0.18 Vetinari

### ISSUE THREAD

**Issue by fun29** [surrim/vlc-delete#15]
See debug output attached, the file still exists after using the "Remove current file" menu-item.

Error in the debug log:
`lua info: [vlc-delete] error: File does not exist`

[vlc.debug.txt](https://github.com/surrim/vlc-delete/files/11760524/vlc.debug.txt)

**Comment by surrim** [comment]
Thanks for your report. Was there anything special with the filename? Unicode letters, network drive, etc?

**Comment by fun29** [comment]
Initially yes. Then I renamed it to something like "abc.mp4" and it still failed.
So that's when I decided to report it with the full vlc debug log. You can see the filename there also.

**Comment by surrim** [comment]
> lua info: [vlc-delete] removing: G:/file.mp4

Can you try to get some more information/debug the script please? Maybe my [windows detection](https://github.com/surrim/vlc-delete/blob/537ba98da2d3c18ead5c805db06ee5b99c319e8c/vlc-delete.lua#LL73C25-L73C25) is not working for Win10.
I'm using Linux since 2004, and I never had something newer than Win 7 to test.

**Comment by fun29** [comment]
The "File does not exist" only exists in function windowsDelete so it seems to detect windows.

Perhaps the gsub, translating / into \ does not work?

```
lua info: [vlc-delete] removing: G:/file.mp4
main info: playlist is empty
lua info: [vlc-delete] error: File does not exist
```

**Comment by fun29** [comment]
I've tried hardcoding the filename:

```
function windowsDelete()
vlc.msg.info("[vlc-delete] before")
local file = "G:\file.mp4"
os.remove(file)
vlc.msg.info("[vlc-delete] after")
end
```

That results in:

```
qt debug: activating or triggering extension 'VLC Delete'
lua debug: Activating extension 'VLC Delete'
lua info: [vlc-delete] removing: G:/file.mp4
main debug: deleting item `file.mp4'
lua info: [vlc-delete] before
main debug: incoming request - stopping current input
lua info: [vlc-delete] after
lua warning: Error while running script C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua, function activate(): C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua:106: attempt to concatenate global 'err' (a nil value)
lua error: Could not activate extension!
lua debug: Deactivating 'VLC Delete'
lua debug: Deactivating 'VLC Delete'
```

**Comment by fun29** [comment]
Also tried this:

```
function windowsDelete()
vlc.msg.info("[vlc-delete] before")
local file = "G:\\file.mp4"
os.remove(file)
vlc.msg.info("[vlc-delete] after")
end
```

That results in:

```
qt debug: activating or triggering extension 'VLC Delete'
lua debug: Activating extension 'VLC Delete'
lua info: [vlc-delete] removing: G:/file.mp4
main debug: deleting item `file.mp4'
lua info: [vlc-delete] before
main debug: incoming request - stopping current input
lua info: [vlc-delete] after
lua warning: Error while running script C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua, function activate(): C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua:106: attempt to concatenate global 'err' (a nil value)
lua error: Could not activate extension!
lua debug: Deactivating 'VLC Delete'
lua debug: Deactivating 'VLC Delete'
```

**Comment by fun29** [comment]
Also tried this:

```
function windowsDelete()
vlc.msg.info("[vlc-delete] before")
local file = "G:/file.mp4"
os.remove("G:/file.mp4")
vlc.msg.info("[vlc-delete] after")
end
```

That results in:

```
lua debug: Activating extension 'VLC Delete'
lua info: [vlc-delete] removing: G:/file.mp4
main debug: deleting item `file.mp4'
lua info: [vlc-delete] before
main debug: incoming request - stopping current input
main debug: incoming request - stopping current input
lua info: [vlc-delete] after
lua warning: Error while running script C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua, function activate(): C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua:106: attempt to concatenate global 'err' (a nil value)
lua error: Could not activate extension!
lua debug: Deactivating 'VLC Delete'
lua debug: Deactivating 'VLC Delete'
```

**Comment by fun29** [comment]
Alsot tried this:

```
function windowsDelete(file)
f = io.open(file, "r")
vlc.msg.info("[vlc-delete] before")
f:close()
vlc.msg.info("[vlc-delete] after io.close")
os.remove(file)
vlc.msg.info("[vlc-delete] after os.remove")
end
```

That results in:

```
lua debug: Activating extension 'VLC Delete'
lua info: [vlc-delete] removing: G:/file.mp4
main debug: deleting item `file.mp4'
main debug: incoming request - stopping current input
lua info: [vlc-delete] before
lua info: [vlc-delete] after io.close
lua info: [vlc-delete] after os.remove
lua warning: Error while running script C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua, function activate(): C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete.lua:108: attempt to concatenate global 'err' (a nil value)
lua error: Could not activate extension!
lua debug: Deactivating 'VLC Delete'
lua debug: Deactivating 'VLC Delete'
```

Which indicates that something is wrong in:

```
	if (retval == nil) then
		vlc.msg.info("[vlc-delete] error: " .. err)
```

**Comment by fun29** [comment]
I've put this code in a lua file and tested it.

https://github.com/surrim/vlc-delete/issues/11#issue-1318914345

It works.

So please "just" "merge" that with your main version.

**Comment by surrim** [comment]
Thanks a lot for your work @fun29, merged with https://github.com/surrim/vlc-delete/commit/539dc60a2f41f51d74884e335ac465d6d597c680. Please check if it's working and don't hesitate to write feedback.

I will make a few more minor changes, not related to this issue.

**Comment by fun29** [comment]
I've tried your new version. Result below:

Output:

![cannotdelete](https://github.com/surrim/vlc-delete/assets/52833515/1063693a-4eb7-4745-98f0-b4552323fdd2)

```
lua debug: Activating extension 'VLC Delete'
lua info: [vlc-delete] removing: G:\file.mp4
lua info: [vlc-delete] error: File does not exist
lua debug: Creating dialog 'VLC Delete'
qt debug: Creating a new dialog: 'VLC Delete'
lua debug: Clicking 'C:\Apps\vlc-3.0.18\lua\extensions\vlc-delete-prerelease.lua': 'OK'
lua debug: Deleting dialog 'VLC Delete'
lua debug: Waiting for the dialog to be deleted...
qt debug: Deleting extension dialog 'VLC Delete'
lua debug: Deactivating 'VLC Delete'
lua debug: Deactivating 'VLC Delete'
```

**Comment by surrim** [comment]
Could you check the result of `if exists` [here](https://github.com/surrim/vlc-delete/blob/be81cf542e36fc910a16fad21ea437f96ba34272/vlc-delete.lua#L37)?
I included this function to test the result of the `del` command. `del` always returns 0 / no error.

**Comment by surrim** [comment]
Maybe

```
function file_exists(file)
	retval, err = os.execute("if exist \"" .. file .. "\" (exit 0) else (exit 1)")
	return type(retval) == "number" and retval == 0
end
```

works. At least my wine test gets the right exitcode.

**Comment by fun29** [comment]
The `if exists` is there.

When I replace the file_exists function with [your suggestion](https://github.com/surrim/vlc-delete/issues/15#issuecomment-1595864735), deleting the file works 🙏

I do see 3 cmd.exe popups when it deletes the file. The [other working](https://github.com/surrim/vlc-delete/issues/11#issue-1318914345) solution "only" has 2.

The ideal solution does not have any popups.

**Comment by surrim** [comment]
Included in https://github.com/surrim/vlc-delete/commit/6f5f2766118870a73dd42a0a7100f53ff31b33c5

3 popups are perfect, if it's not from [3 attempts](https://github.com/surrim/vlc-delete/blob/6f5f2766118870a73dd42a0a7100f53ff31b33c5/vlc-delete.lua#LL51C9-L51C9) to delete the file.
Normally the popups are
1. check if the file exists before (e.g. not working for unicode files)
2. the `del` command
3. check if the file exists after

It would be much easier if `del` would return a proper exitcode. On Linux you don't see popups at all. The best solution would be to use Lua's `os.remove()` command - but unfortunately it can't handle unicode filenames.
