### ISSUE TITLE
add Hotkey to vlc-delete

### ISSUE THREAD

**Issue by thorizer** [surrim/vlc-delete#3]
Can we add a hotkey to vlc-delete ?

**Comment by surrim** [comment]
I tried this in the past, but I found no way to do that. Feel free to modify, it's open source ;-)

**Comment by surrim** [comment]
It seems that it's not possible to use hotkeys, see [https://forum.videolan.org/...](https://forum.videolan.org/viewtopic.php?p=450085).

**Comment by DanKaplanSES** [comment]
On Windows, you can install [AutoHotKey](https://www.autohotkey.com/) v1 and use this script to trigger the menu item (as though you typed `alt+i,r`) to the shortcut `ctrl+delete`:

```ahk
#IfWinActive ahk_exe vlc.exe
^Delete::
SendInput {Blind}{Ctrl up}{Delete up}
SendInput {Blind}{Alt down}{i down}{i up}{r down}{r up}{Alt up}
```

**Comment by abramter** [comment]
> On Windows, you can install [AutoHotKey](https://www.autohotkey.com/) v1 and use this script to trigger the menu item (as though you typed `alt+i,r`) to the shortcut `ctrl+delete`:
> 
> ```ahk
> #IfWinActive ahk_exe vlc.exe
> ^Delete::
> SendInput {Blind}{Ctrl up}{Delete up}
> SendInput {Blind}{Alt down}{i down}{i up}{r down}{r up}{Alt up}
> ```


For AutoHotKey v2, you can use this one.
```ahk
#Requires AutoHotkey v2.0

#HotIf WinActive("ahk_exe vlc.exe")
^Delete:: {
    Send("{Blind}{Ctrl up}{Delete up}")
    Send("{Blind}{Alt down}{i down}{i up}{r down}{r up}{Alt up}")
}
#HotIf
```

**Comment by surrim** [comment]
> For AutoHotKey v2, you can use this one.

@DanKaplanSES, @abramter: I placed the snippet into the doc, see https://github.com/surrim/vlc-delete/commit/94c6e4efa6664dae594bcfb1721dd1e0a18a6f66
Thanks for contributing 🚀
