### ISSUE TITLE
bind key

### ISSUE THREAD

**Issue by ericsia** [surrim/vlc-delete#7]
can you update to bind the shortcut key to [shift + delete] ?

**Comment by PeterFuhren** [comment]
Maybe a stupid question to ask, but... what's the current shortcut key

**Comment by surrim** [comment]
Please see here: https://github.com/surrim/vlc-delete/pull/6
I think it's not possible to bind any keys like shift+delete. But I'm not LUA expert. The best might be to send a pull request.

**Comment by ericsia** [comment]
> Please see here: #6 I think it's not possible to bind any keys like shift+delete. But I'm not LUA expert. The best might be to send a pull request.

> access key notation "&(menu text)"

I didn't get what he means by that 🤔

**Comment by surrim** [comment]
@ericsia @PeterFuhren :heavy_check_mark: I fixed that problem, see https://github.com/surrim/vlc-delete/issues/10#issuecomment-1341840927.
