### ISSUE TITLE
Does not work with Windows UNC paths

### ISSUE THREAD

**Issue by Taomyn** [surrim/vlc-delete#8]
When directly viewing files on a Windows UNC path e.g. \\SERVER\Share\File.mp4 it says the file does not exist.

I also could not see from the script if the video is stopped before it deletes because VLC has a nasty habit of locking the file until it opens  the next one.

**Comment by freeload101** [comment]
workaround 
net use p: "\\uncpath" ..

**Comment by surrim** [comment]
The only commands which might work are `net use` and `pushd`. But there's no native way to do it with Lua scripts - so I won't fix it.
Another problem is that I have no Windows system for testing, so I could only write some lines and "hope" that it works.
Anyway, feel free to contribute ❤️

**Comment by surrim** [comment]
Workaround mentioned in the **Known bugs and issues** section
